...
deployment:
  tasks:
    - export DEPLOYPATH=/home/contro15/public_html/sotramin/
    - /bin/cp build/  $DEPLOYPATH
    - /bin/cp .htaccess  $DEPLOYPATH
    - /bin/cp favicon.ico  $DEPLOYPATH
    - /bin/cp robots.txt  $DEPLOYPATH
   